---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Set up the Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }}
    state: present

- name: Install Docker
  apt:
    name: docker-ce={{ docker_version }}
    state: present

- name: Ensure Docker is started and enabled
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Download Docker Compose binary
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-$(uname -s)-$(uname -m)"
    dest: /usr/local/bin/docker-compose
    mode: 'u+x'

- name: Ensure Docker Compose is executable
  file:
    path: /usr/local/bin/docker-compose
    mode: 'u+x'

