---
- name: Build the Docker image
  docker_image:
    name: "{{ docker_image_name }}"
    tag: "{{ docker_image_tag }}"
    source: build
    build:
      path: "{{ docker_build_path }}"
      dockerfile: "{{ dockerfile_path }}"
          
- name: Log in to Docker Hub
  docker_login:
    username: "{{ dockerhub_username }}"
    password: "{{ dockerhub_token }}"

- name: Push the Docker image to Docker Hub
  docker_image:
    name: "{{ docker_image_name }}"
    tag: "{{ docker_image_tag }}"
    repository: "{{ dockerhub_repo }}"
    push: true
    source: local
